Firmware/RTK_Surveyor/Tasks.ino
=> RTK Surveyor states

Firmware/RTK_Surveyor/States.ino, Firmware/RTK_Surveyor/System.ino
Report heap free space upon:
1. State changes
2. Bluetooth start
3. Bluetooth stop
4. WiFi start
5. WiFi stop
=> Add reportHeapNow function and report free space during state changes

Firmware/RTK_Surveyor/Begin.ino, Firmware/RTK_Surveyor/Buttons.ino, Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/System.ino, Firmware/RTK_Surveyor/Tasks.ino, Firmware/RTK_Surveyor/menuFirmware.ino, Firmware/RTK_Surveyor/menuMain.ino, Firmware/RTK_Surveyor/menuMessages.ino, Firmware/RTK_Surveyor/menuSystem.ino
The semaphore is protecting access to the SPI controller used to access
the SD card.  Any operations to the SD card need to be protected by this
semaphore.
=> Change semaphore name from xFATSemaphore to sdCardSemaphore

u-blox_Update_GUI/RTK_u-blox_Update_GUI.py
If your module is really in a mess, you may need to:
* Disable safeboot (and training sequence)
* Select the override option
=> Add checkboxes for safeboot and training sequence etc.

docs/gis_software.md
At the end of the SurvPC section, readers of the document are encouraged to contact Carlson Software and ask Carlson to incorporate support for SparkFun RTK into SurvPC.  If the long term goal is to have a working relationship with Carlson, let's not antagonize Carlson.  Therefore I suggest we remove the "hostile" language from the intro to SurvPC, however accurate it may be in describing someone's experiences.
=> Update gis_software.md intro to Carlson SurvPC

docs/firmware_update.md
Updated firmware build instructions:
*  Added virtual machine setup
*  The Arduino IDE seems to be using Python3 to upload files
*  Switched from Python2 to Python3 - requires switching esptool.py file
*  Add a few more high level comments
*  Reordered the sequence to group like things together
=> Update the Linux build instructions

Firmware/RTK_Surveyor/Begin.ino, Firmware/RTK_Surveyor/Buttons.ino, Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/SD.ino, Firmware/RTK_Surveyor/States.ino, Firmware/RTK_Surveyor/System.ino, Firmware/RTK_Surveyor/Tasks.ino, Firmware/RTK_Surveyor/menuFirmware.ino, Firmware/RTK_Surveyor/menuMain.ino, Firmware/RTK_Surveyor/menuMessages.ino, Firmware/RTK_Surveyor/menuSystem.ino
With this change, I recommend only removing the microSD card when the RTK power is off or logging is not enabled.  Removing the microSD card when the RTK is powered on and logging is enabled is likely to corrupt the microSD card!
This change leaves the microSD card mounted anytime logging is enabled.  When logging is disabled the microSD card is dismounted.  All references to the microSD card are protected by the sdCardSemaphore.  References to the SD card while the system is active cause the SD card to be mounted first and then dismounted following the reference.  Listing the microSD card files from the Serial Config System menu, updating the firmware from the Serial Config Debug menu or via WiFi config are examples of this behavior.
The settings on the microSD card will override the …
=> Dynamically mount and dismount the microSD Card

Firmware/RTK_Surveyor/menuMessages.ino
The GNSS is properly returning the UTC date and time which was used to
set the RTC.  The request to get the hours from the RTC was fetching the
0 - 11 value instead of the 0 - 23 value.  This change fetches the 0 -
23 value from the RTC for the hours.
=> Fix file dates by getting 24 hour instead of 12 hour time from the RTC

Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/menuMessages.ino, Firmware/RTK_Surveyor/menuSystem.ino, Firmware/RTK_Surveyor/settings.h
Add the ability to set the time zone (hours, minutes and seconds) to the system menu.  The default for these values is zero.  Adjust the real time clock (RTC) based upon the time zone offset.  The RTC clock value is used for the file time stamps.
=> Add Time zone support

Firmware/RTK_Surveyor/NtripClient.ino
ntripClientStop is being called from startBluetooth in System.ino.
Promote ntripClientStop from local to global to support the no WiFi builds.
=> Fix build error with no WiFi

Firmware/RTK_Surveyor/AP-Config/index.html, Firmware/RTK_Surveyor/AP-Config/src/main.js, Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/form.h
Pass the profile number to WiFi config.  Update the profile number and
settings file name if WiFi Config changed the profile number value.
Update the profile name in the list of active profile names.
=> WiFi Config: Enable modification of profileName and profileNumber

Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/menuMain.ino
Add setProfileName routine to copy the profile name from settings into
the profile name array.  This routine also sets the activeProfile bit.
Use setProfileName in Form.ino and menuMain.ino.
Use setSettingsFileName in menuMain.ino, already in use by Form.ino.
=> Set active profile bit when profile name is changed

Firmware/RTK_Surveyor/AP-Config/index.html, Firmware/RTK_Surveyor/AP-Config/src/main.js, Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/form.h
In the Profile Configuration section:
* Displays the list of profile name
* Displays the boot profile number
* Allows entry of the boot profile number
* When the parameters are saved, updates the boot profile number
Does not update the name in the profile list on WiFi Config page when a profile name is changed.
=> Display the profile names and select the boot profile using WiFi Config

Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/Tasks.ino
Use a ring buffer to eliminate loss of data.  The 6 KB ring buffer can
hold about 2 seconds of data.  This should be able to dump the entire
buffer to Bluetooth in under a second and easily write the entire buffer
to the microSD card within that time.
Compiling with the Core Debug Level set to Debug and entering Serial
Config to list the microSD card files should generate the warning about
the SD card semaphore not being released.  There may need to be a large
number (~100) of files on the microSD card.
I have left the Bluetooth congestion error and the sdCardSemaphore error
in the serial output (customer visible) so that we may get customer
feedback if these errors ever occur.
=> Added ring buffer to F9PSerialReadTask

Firmware/RTK_Surveyor/Display.ino, Firmware/RTK_Surveyor/NtripServer.ino, Firmware/RTK_Surveyor/Tasks.ino, Firmware/RTK_Surveyor/settings.h
When not connected to the NTRIP caster either via Bluetooth or WiFi,
display the Casting Off or Xmitting Off message on the RTK Express, RTK
Express Plus or RTK Facet display.  This occurs when:
*  Using Bluetooth and no Bluetooth connection
*  Using WiFi instead of Bluetooth and no WiFi NTRIP caster connection
=> Display Casting Off or Xmitting Off when not connected

Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/menuSystem.ino, Firmware/RTK_Surveyor/settings.h
Add debug menu items to print:
* Battery messages
* Rover Accuracy messages
* Messages with bad checksums or CRCs
* Log file messages
* NTRIP server messages (already in debug menu)
* NTRIP client messages
=> Add debug menu items to print messages

Firmware/RTK_Surveyor/NtripServer.ino
Requires [#262](https://github.com/sparkfun/SparkFun_RTK_Firmware/pull/262)
=> Initialize the NTRIP server parser before entering the caster state

Firmware/RTK_Surveyor/Begin.ino, Firmware/RTK_Surveyor/Bluetooth.ino, Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/bluetoothSelect.h, Firmware/RTK_Surveyor/menuBluetooth.ino, Firmware/RTK_Surveyor/menuMain.ino, Firmware/RTK_Surveyor/settings.h, Firmware/RTK_Surveyor/src/BleSerial/BleSerial.cpp, Firmware/RTK_Surveyor/src/BleSerial/BleSerial.h, Firmware/RTK_Surveyor/src/BleSerial/ByteRingBuffer.h
See PR #235 for the original description and change. 
Note: I'd like to test this change a bit more after issue #237 is resolved. I'm not 100% sure that bug is only adding noise. It might also be mangling some of the GNSS messages as well.
@nseidle I think I addressed your first to points. For the 3rd (bluetoothSerial library moving to its own repo soon), is there anything you'd like me to do as part of this change for that? I think it should be pretty easy to split the two bluetooth serial libraries into external dependencies once you're ready.
Thanks!
=> Add BLE Support

Firmware/RTK_Surveyor/Begin.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/Tasks.ino, Firmware/RTK_Surveyor/menuGNSS.ino, Firmware/RTK_Surveyor/menuMain.ino, Firmware/RTK_Surveyor/menuMessages.ino, Firmware/RTK_Surveyor/menuSystem.ino, Firmware/RTK_Surveyor/settings.h
The log test allows us to record a series of different system configurations into one file. At the same time, we log the output of the ZED via the USB connection. Once complete, the SD log is compared against the USB log to verify both are identical. Be sure to set maxLogLength_minutes before running test. maxLogLength_minutes will set the length of each test.
=> Add log test to debug menu

Firmware/RTK_Surveyor/Begin.ino, Firmware/RTK_Surveyor/Bluetooth.ino, Firmware/RTK_Surveyor/Display.ino, Firmware/RTK_Surveyor/ESPNOW.ino, Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/menuMain.ino, Firmware/RTK_Surveyor/menuPP.ino, Firmware/RTK_Surveyor/menuSystem.ino
The ESP32 is assigned 4 MAC addresses but only the base address is
stored in the fuses and is accessible by calling esp_read_mac.  The MAC
address are documented at
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/misc_system_api.html#mac-address:
1. WiFi Station: Base MAC address
2. WiFi AP:      Base MAC address + 1
3. Bluetooth:    Base MAC address + 2
4. Ethernet:     Base MAC address + 3
L-Band is currently using the Bluetooth address for identification but
the code actually use the WiFi Station address when provisioning the
RTK.
=> Properly display and use the MAC addresses

Firmware/RTK_Surveyor/Begin.ino, Firmware/RTK_Surveyor/Bluetooth.ino, Firmware/RTK_Surveyor/Display.ino, Firmware/RTK_Surveyor/ESPNOW.ino, Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/menuMain.ino, Firmware/RTK_Surveyor/menuPP.ino, Firmware/RTK_Surveyor/menuSystem.ino
Requires [#295](https://github.com/sparkfun/SparkFun_RTK_Firmware/pull/295)
Move the Bluetooth test code into Bluetooth.ino.
Add a parameter to the test code to enable/disable running the test.
Use the common code in the System menu to just display the Bluetooth status.
Add a menu item to the Debug menu to run the Bluetooth test.
Display Bluetooth test results all at once to allow additional messages to be displayed during the test.
=> Move Bluetooth test into Debug menu

Firmware/Tools/NMEA_Client.c
Enable the NMEA client program to forward data from the RTK NMEA TCP
server to the Vespucci NMEA server.
Use this on a local WiFi network.  Both the RTK and the Android phone
need to connect to the local WiFi network.  This NMEA client program
eliminates the RTK NMEA client code and validates the Android connection
to the Vespucci NMEA server.  Once the Android connection is working, it
is easy to enable the RTK NMEA client by enabling the Mobile Hot Spot on
the phone and switching the WiFi SSID and password in the RTK.
=> Update the NMEA client support program

Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/menuPP.ino
**This change has not been tested**
`09:32:28.918 -> Connecting to: https://api.thingstream.io/ztp/pointperfect/credentials`
`09:32:28.918 -> HTTP response error 422: {"errors":["token invalid token format"]}`
This change includes:
* Move certificateContents and keyContents into menuPP.ino
* Rework updatePointPerfectKeys to have a single exit
* Always disconnect the MQTT client if it was connected.
* Allocate and free the context buffers
=> Allocate and free the L-Band context buffers

Firmware/RTK_Surveyor/Tasks.ino
Requires: [#294](https://github.com/sparkfun/SparkFun_RTK_Firmware/pull/294) and [#297](https://github.com/sparkfun/SparkFun_RTK_Firmware/pull/297)
Empty all of the UART data into the ring buffer before attempting to send any data over Bluetooth or log any data.
=> Empty UART data into ring buffer then send data

Firmware/RTK_Surveyor/menuMessages.ino
Issue detected: Short log file, captured only 40 minutes when the
maximum log time was set to 60 minutes.
Steps to reproduce:
1. Enter the serial configuration
2. Enter 5 to enter the Logging Menu
3. If logging is disabled, enter 1 to enable logging
4. Enter 2 and then 60 to set the maximum log time to 60 minutes
5. If the maximum log length < 60 minutes then enter 3 and enter a value
greater than or equal to 60 for the maximum log length to produce a
single file containing all of the log data
6. Exit the serial configuration menus
7. After about 5 minutes, enter the serial configuration and disable
logging
8. After about another 15 minutes, enter the serial configuration and
enable logging
9. After an hour the logging should have stopped and the last log file
should contain data that is …
=> Reset the maximum logging time when logging is disabled

Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/Tasks.ino, Firmware/RTK_Surveyor/WiFi.ino, Firmware/RTK_Surveyor/menuSystem.ino, Firmware/RTK_Surveyor/settings.h
Requires #294 through #298
Testing done with Bluetooth disabled:
* Verified client disconnect is detected and closes ESP32 NMEA socket
* Verified disabling NMEA TCP via system menu closes ESP32 NMEA socket
* Verified wifiStop while NMEA client active closes ESP32 NMEA socket
* Switching from Rover to Base closes ESP32 NMEA socket
* Switching from Base to Rover closes ESP32 NMEA socket
=> Add NMEA TCP to the ring buffer

Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/Tasks.ino, Firmware/RTK_Surveyor/WiFi.ino, Firmware/RTK_Surveyor/menuSystem.ino, Firmware/RTK_Surveyor/settings.h
Requires: #297, #298, #299
Support using a phone as a WiFi hot spot.  The RTK NMEA TCP client connects to the gateway IP address (the phone's WiFi hot spot) on port 1958.  If an application such as Vespucci is running as a NMEA server using port 1958, then the RTK will connect to the application.
Android WiFi Settings
1.  Disable WiFi
2.  Enable Mobile Hot Spot
3.  Set the Network Name
4.  Set the Network Password
5.  Set the Band to 2.4 GHz
6.  Enable Wi-Fi sharing - This enables users of the Hot Spot to talk to applications on the phone
In Vespucci:
1.  Click on the gear icon
2.  Select "Advanced preferences"
3.  Select "Location settings"
4.  Select "GPS/GNSS source"
5.  Select "NMEA from TCP server"
6.  Select "NMEA network source"
7.  Enter an IP address immediately followed by a …
=> Enable NMEA TCP client - Connect to phone

Firmware/RTK_Surveyor/Base.ino, Firmware/RTK_Surveyor/Begin.ino, Firmware/RTK_Surveyor/Bluetooth.ino, Firmware/RTK_Surveyor/NtripClient.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/Rover.ino, Firmware/RTK_Surveyor/States.ino, Firmware/RTK_Surveyor/System.ino, Firmware/RTK_Surveyor/Tasks.ino, Firmware/RTK_Surveyor/menuBase.ino, Firmware/RTK_Surveyor/menuFirmware.ino, Firmware/RTK_Surveyor/menuGNSS.ino, Firmware/RTK_Surveyor/menuMessages.ino, Firmware/RTK_Surveyor/menuPP.ino, Firmware/RTK_Surveyor/menuPorts.ino, Firmware/RTK_Surveyor/menuSystem.ino
Move away from deprecated u-blox method.
=> Configure module using keys

docs/firmware_update.md
This commit includes the following changes:
* Added directions on how to clone the RTK binaries
* Updated new-firmware.sh to use the RTK binaries
* Added new-firmware-4mb.sh for use when programming older RTK devices
=> Docs: Updated new-firmware.sh and added new-firmware-4mb.sh

Firmware/RTK_Surveyor/Base.ino, Firmware/RTK_Surveyor/Begin.ino, Firmware/RTK_Surveyor/Bluetooth.ino, Firmware/RTK_Surveyor/Display.ino, Firmware/RTK_Surveyor/ESPNOW.ino, Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/NtripClient.ino, Firmware/RTK_Surveyor/NtripServer.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/Rover.ino, Firmware/RTK_Surveyor/States.ino, Firmware/RTK_Surveyor/System.ino, Firmware/RTK_Surveyor/Tasks.ino, Firmware/RTK_Surveyor/WiFi.ino, Firmware/RTK_Surveyor/bluetoothSelect.h, Firmware/RTK_Surveyor/menuBase.ino, Firmware/RTK_Surveyor/menuFirmware.ino, Firmware/RTK_Surveyor/menuGNSS.ino, Firmware/RTK_Surveyor/menuMain.ino, Firmware/RTK_Surveyor/menuMessages.ino, Firmware/RTK_Surveyor/menuPP.ino, Firmware/RTK_Surveyor/menuPorts.ino, Firmware/RTK_Surveyor/menuSystem.ino, Firmware/RTK_Surveyor/settings.h, Firmware/RTK_Surveyor/support.ino
This PR changes all system prints to be directed at the local Serial.print, or Bluetooth.print, or both. This allows a user to use a Bluetooth serial app to control and configure the RTK device, without the need for the WiFi config page. 
To enter the 'Bluetooth Echo' mode:
* Open a bluetooth serial app such as [Serial Bluetooth Terminal for Android](https://play.google.com/store/apps/details?id=de.kai_morich.serial_bluetooth_terminal&hl=en_US&gl=US&pli=1)
* Connect to the RTK Device
* Send the string +++
To exit the 'Bluetooth Echo' mode:
* Select 'b' from the configuration menu
=> Allow system serial over Bluetooth

Firmware/RTK_Surveyor/AP-Config/index.html, Firmware/RTK_Surveyor/AP-Config/src/main.js, Firmware/RTK_Surveyor/Display.ino, Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/NtripClient.ino, Firmware/RTK_Surveyor/NtripServer.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/States.ino, Firmware/RTK_Surveyor/WiFi.ino, Firmware/RTK_Surveyor/form.h, Firmware/RTK_Surveyor/menuBase.ino, Firmware/RTK_Surveyor/menuGNSS.ino, Firmware/RTK_Surveyor/menuMain.ino, Firmware/RTK_Surveyor/menuPP.ino, Firmware/RTK_Surveyor/menuSystem.ino, Firmware/RTK_Surveyor/settings.h, Firmware/RTK_Surveyor/support.ino
This PR:
* Consolidates NTRIP Client, NTRIP Server, and PointPerfect Home WiFi/PW credentials into a single list of up to four networks. All four networks are attempted when WiFi is needed, and the best network is automatically used. 
* Add a WiFi menu to serial config and to the WiFi AP config page.
* Add TCP server and client controls to AP config page. Fix for #358.
* Make TCP port user configurable. Add to AP config page.
* Add option to allow WiFi configure over local WiFi (as opposed to AP).
* Change how IP addresses are shown on display.
=> WiFi network consolidation

docs/system_configuration.md
I found on the web page that these were broken.  Looking into the details they had an extra "docs\" in front of each sub-menu.  It displayed as docs%5C, and each hyper-link went to "404 Not Found".  This fixes the problem.
=> Fix HyperLinks to system_configuration sub-menus

docs/connecting_bluetooth.md
I got stuck here for half a day trying to configure the device to work with my iPhone.  I couldn't understand why it wouldn't pair with my phone when it paired just fine with my computer.  Finally I read ahead in the instructions and at the very bottom of the GIS software page I found this nugget of information.  I almost missed it since most of the GIS software was not relevant to me.  I recommend moving this nugget of information up a page so others don't get stuck here quite so easily.
=> Add information on iOS BLE to Bluetooth Page

Firmware/RTK_Surveyor/NtripServer.ino
* Start ntripServerTimer when starting the network
* Restart after 1 minute if network does not start
* Reorder authorization failover cases to ensure that all are covered
=> NTRIP Server: Fix WiFi retry cases

Firmware/RTK_Surveyor/NtripServer.ino
* Start ntripServerTimer when starting the network
* Restart after 1 minute if network does not start
* Reorder authorization failover cases to ensure that all are covered
=> NTRIP Server: Remove extra code

Firmware/RTK_Surveyor/NtripClient.ino
* Start ntripClientTimer when starting the network
* Restart after 1 minute if network does not start
* Reorder authorization failover cases to ensure that all are covered
=> NTRIP Client: Remove unnecessary ntripClientStop()

Firmware/RTK_Surveyor/Begin.ino, Firmware/RTK_Surveyor/Display.ino, Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/NtripClient.ino, Firmware/RTK_Surveyor/NtripServer.ino, Firmware/RTK_Surveyor/menuFirmware.ino, Firmware/RTK_Surveyor/menuMain.ino, Firmware/RTK_Surveyor/menuMessages.ino, Firmware/RTK_Surveyor/menuPP.ino
* Prefix of d when ENABLE_DEVELOPER is set
* Prefix of v for other versions
=> Use a consistent format for the version number

Firmware/RTK_Surveyor/menuSystem.ino
This prevents a system crash and possible corruption of the SD card
=> Bug fix: Shutdown UART2 tasks before changing the ring buffer size

Firmware/RTK_Surveyor/Form.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/WiFi.ino
This pull request shows the configuration website as a [captive portal](https://en.wikipedia.org/wiki/Captive_portal) for reducing the number of steps required to configure the RTK receiver via the web interface.
Therefore it is required to run a DNS server on the ESP32 and intercept the automatic requsts by the connected mobile device. The intercepted request on the in the wiki defined URLs are answered by a additional AsyncWebHandler that provides a small website redirecting the user to the configuration web interface. This extra step is required, because a simple HTTP redirct did not work in testing and the default index.html did not request the configuration data correctly. 
Previously the user would connect to the WiFi AP, read the IP on the RTK Express screen, type the IP into the …
=> Captive Portal for easy configuration

Firmware/RTK_Surveyor/Network.ino
Fix 7 second WiFi restart when NTRIP shuts down due to connection attempts exceeded.
=> Network: Don't restart network with no users

Firmware/RTK_Surveyor/NVM.ino, Firmware/RTK_Surveyor/NtripClient.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/Tasks.ino, Firmware/RTK_Surveyor/ZED.ino, Firmware/RTK_Surveyor/menuPP.ino, Firmware/RTK_Surveyor/menuSystem.ino, Firmware/RTK_Surveyor/settings.h
Testing shows that the ZED gets confused (positional accuracy bounces around a lot) if both PMP and RTCM are fed into the ZED.
=> Turn off L-Band if RTCM is received

Firmware/RTK_Surveyor/Developer.ino, Firmware/RTK_Surveyor/NTP.ino, Firmware/RTK_Surveyor/Network.ino, Firmware/RTK_Surveyor/NtripClient.ino, Firmware/RTK_Surveyor/NtripServer.ino, Firmware/RTK_Surveyor/OtaClient.ino, Firmware/RTK_Surveyor/PvtClient.ino, Firmware/RTK_Surveyor/PvtServer.ino, Firmware/RTK_Surveyor/PvtUdpServer.ino, Firmware/RTK_Surveyor/RTK_Surveyor.ino, Firmware/RTK_Surveyor/States.ino, Firmware/RTK_Surveyor/settings.h
Define the RTK operating modes and set these modes in States.ino.
For each network user:
* Add a bit mask specifying which modes the network user is active
* Stop the network user when the enable or mode changes
* Start the network user when the mode and enable are set
=> Network clients start and stop depending upon operating modes

Firmware/RTK_Surveyor/Bluetooth.ino, Firmware/RTK_Surveyor/menuPP.ino
* Fix MQTT key checking
* Fix Bluetooth name when state is out of range
=> Merge v4.0 changes

Firmware/RTK_Surveyor/NtripServer.ino
Allows NTRIP server connection failures to occur without breaking the NTRIP server connection to another server.
=> Increase the RTCM transmit timeout from 3 seconds to 15 seconds

Firmware/RTK_Surveyor/AP-Config/index.html
Reference station doesn't accept values above 600 seconds for survey-in while the help text suggests values up to and including 900 seconds are acceptable.
=> Fix wrong survey-in time limit in help text

docs/menu_ports.md, docs/menu_tcp_udp.md
This PR contains two commits, each documented in its commit message.
The first clarifies the TCP server feature.  The second notes which UART the data port is connected to.
Thanks to forum users for help understanding.
=> Clarify docs: TCP server, radio UART
